# Generated by Django 2.2.7 on 2019-12-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191120_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
