# Generated by Django 2.2.8 on 2019-12-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20191227_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='../static/item/img/default_item_image.png', upload_to='img/'),
        ),
    ]
